## Exercises & Extra-curriculum

In [ ]:
# Create a random tensor with shape (7, 7)
tensor = torch.rand(7, 7)
tensor

tensor([[0.5615, 0.9716, 0.1067, 0.1639, 0.2931, 0.7575, 0.8479],
        [0.9626, 0.6163, 0.3998, 0.1384, 0.9873, 0.6493, 0.7202],
        [0.9203, 0.1727, 0.1101, 0.9782, 0.7518, 0.3760, 0.8973],
        [0.1630, 0.9578, 0.7372, 0.5823, 0.5942, 0.0728, 0.2413],
        [0.8703, 0.0731, 0.5561, 0.3371, 0.2547, 0.0390, 0.2572],
        [0.6162, 0.0523, 0.3733, 0.0177, 0.1526, 0.6109, 0.7568],
        [0.8437, 0.7030, 0.0113, 0.9053, 0.6020, 0.6001, 0.7988]])

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
# (hint: you may have to transpose the second tensor)
another_tensor = torch.rand(1, 7)

# solution 1
tensor.matmul(another_tensor.T)

# solution 2
another_tensor @ tensor

tensor([[2.0476, 1.8241, 0.9404, 1.5810, 1.6164, 1.4844, 2.1043]])

In [ ]:
# Set the random seed to 0 and do exercises 2 & 3 over again
torch.manual_seed(0)
tensor = torch.rand(7, 7)
print(f"step 2: {tensor}")

torch.manual_seed(0)
another_tensor = torch.rand(1, 7)
print(f"step 3: {another_tensor}")
print(f"step 3 matmul: {tensor.matmul(another_tensor.T)}")

step 2: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
step 3: tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
step 3 matmul: tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [ ]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234
torch.cuda.manual_seed(1234)

In [ ]:
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)
torch.manual_seed(1234)
tensor1 = torch.rand(2, 3)
tensor1_gpu = tensor1.to(device)
torch.manual_seed(1234)
tensor2 = torch.rand(2, 3)
tensor2_gpu = tensor2.to(device)

print('tensor1', tensor1_gpu)
print('tensor2', tensor2_gpu)

tensor1 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor2 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


In [ ]:
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)
tensors_matmul = tensor1_gpu @ tensor2_gpu.T
tensors_matmul

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [ ]:
# Find the maximum and minimum values of the output of 7
# min vals
# 1
print('min', tensors_matmul.min())
# 2
print('min', torch.min(tensors_matmul))

# max vals
# 1
print('max', tensors_matmul.max())
# 2
print('max', torch.max(tensors_matmul))

min tensor(0.2161, device='cuda:0')
min tensor(0.2161, device='cuda:0')
max tensor(0.6287, device='cuda:0')
max tensor(0.6287, device='cuda:0')


In [ ]:
# Find the maximum and minimum index values of the output of 7
# min idx
# 1
print('min', tensors_matmul.argmin())
# 2
print('min', torch.argmin(tensors_matmul))

# max vals
# 1
print('max', tensors_matmul.argmax())
# 2
print('max', torch.argmax(tensors_matmul))

min tensor(1, device='cuda:0')
min tensor(1, device='cuda:0')
max tensor(3, device='cuda:0')
max tensor(3, device='cuda:0')


In [ ]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape
torch.manual_seed(7)
tensor = torch.rand(1, 1, 1, 10)
print('tensor', tensor)
print("tensor's shape", tensor.shape)
print('tensor with all 1 dims removed', tensor.squeeze())
print("new tensor's shape", tensor.squeeze().shape)

tensor tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor's shape torch.Size([1, 1, 1, 10])
tensor with all 1 dims removed tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
new tensor's shape torch.Size([10])
